# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpKhheV8ET6nSBWA91jp5qvjP-eOXyxm
"""

import face_recognition
import cv2
import numpy as np

# 0-for defalt, 2- for webcam
video_capture = cv2.VideoCapture(0)

# Training part

# 1 Load image and teach module.
amma_image = face_recognition.load_image_file("images/amma.jpg")
amma_face_encoding = face_recognition.face_encodings(amma_image)[0]
# 2
karun_image = face_recognition.load_image_file("images/karun.jpg")
karun_face_encoding = face_recognition.face_encodings(karun_image)[0]
# 3
ramu_image = face_recognition.load_image_file("images/ramu_o.jpg")
ramu_face_encoding = face_recognition.face_encodings(ramu_image)[0]
# 4
sarvjeet_image = face_recognition.load_image_file("images/ramu_o.jpg")
sarvjeet_face_encoding = face_recognition.face_encodings(sarvjeet_image)[0]

# Create arrays of known(order) face encodings and their names
known_face_encodings = [
    amma_face_encoding,
    karun_face_encoding,
    ramu_face_encoding,
    sarvjeet_face_encoding
]
# names should be in same order as encodings
known_face_names = [
    "Amma",
    "karun",
    "ramu",
    "sarvjeet"
]

# Initialize some variables
face_locations = []
face_encodings = []
face_names = []
process_this_frame = True

# detecton part

while True:
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Resize frame of video to 1/4 size for faster face recognition processing
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

    # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
    rgb_small_frame = small_frame[:, :, ::-1]

    # Only process every other frame of video to save time
    if process_this_frame:
        # Find all the faces and face encodings in the current frame of video
        face_locations = face_recognition.face_locations(rgb_small_frame)
        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

        face_names = []
        for face_encoding in face_encodings:
            # See if the face is a match for the known face(s)
            matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
            name = "Unknown"

            #  use the known face with the smallest distance to the new face to gt best match
            face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
            best_match_index = np.argmin(face_distances)
            if matches[best_match_index]:
                # noinspection PyTypeChecker
                name = known_face_names[best_match_index]

            face_names.append(name)

    process_this_frame = not process_this_frame

    # Display the results
    for (top, right, bottom, left), name in zip(face_locations, face_names):
        # Scale back up face locations since the frame we detected in was scaled to 1/4 size
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4

        # Draw a box around the face
        cv2.rectangle(frame, (left, top), (right, bottom), (255, 0, 0), 2)

        # Draw a label with a name below the face
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (255, 0, 0), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

    # detected frame
    cv2.imshow('Video', frame)

    # Hit 'q' on the keyboard to quit!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release webcam
video_capture.release()
cv2.destroyAllWindows()